[template.environment]
  GQL_HOST = "WordPress URL https://reinuxt.xyz"
  NUXT_IMAGE_DOMAINS = "beautiful-belekoy-7a4be5.netlify.app, reinuxt.xyz"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://reinuxt.xyz/.*"]
